### ISSUE TITLE
not all existing relations are returned

### ISSUE THREAD

**Issue by ookimi** [Suyash458/WiktionaryParser#27] opened 2018-06-28 20:13 UTC
Example query: for the word "white", querying English Wikipedia does not return derived words for the noun part-of-speech. In the entry for "boy", this relation is parsed correctly.

**Comment by C0rn3j** [comment] 2018-07-15 13:23
I kind of created a dupe of this issue on accident, and it has been fixed. You may want to retest and close this issue ^^

https://github.com/Suyash458/WiktionaryParser/issues/33

**Closed** 2018-08-22 16:38 UTC
